{
 "title": "BESS Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Estado de Carga",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT batterystateofcharge FROM etmonitor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatura Baterías",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT batterytemperature FROM etmonitor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Últimos registros de temperatura",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT batterytemperature, time_index FROM etmonitor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Voltaje DC Baterías",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT batteryvoltage, time_index FROM etmonitor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Corriente Baterías",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT batterycurrent, time_index FROM etmonitor LIMIT 50 "
    }
   ]
  }
 ]
}