{
 "title": "Inversores_BESS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Nombre_Inversor",
    "label": "Nombre del inversor",
    "query": "SELECT entity_id \nFROM etinverter;"
   }
  ]
 },
 "panels": [
  {
   "title": "Voltaje DC baterías",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT  batteryvoltage, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  },
  {
   "title": "Corriente Baterías",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT  batterycurrent, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  },
  {
   "title": "AC Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT  loadacl1current, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  },
  {
   "title": "Potencia Baterías",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT  batterypower, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  },
  {
   "title": "Potencia Inversores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT  inverterdcpower, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  },
  {
   "title": "Load AC Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT  loadacpower, time_index, entity_id\r\nFROM  etinverter\r\nWHERE entity_id = '$Nombre_Inversor';"
    }
   ]
  }
 ]
}